export const REVIEW_GET_REQUEST = 'REVIEW_GET_REQUEST'
export const REVIEW_GET_SUCCESS = 'REVIEW_GET_SUCCESS'
export const REVIEW_GET_FAIL = 'REVIEW_GET_FAIL'

export const REVIEW_ADD_REQUEST = 'REVIEW_ADD_REQUEST'
export const REVIEW_ADD_SUCCESS = 'REVIEW_ADD_SUCCESS'
export const REVIEW_ADD_FAIL = 'REVIEW_ADD_FAIL'

export const REVIEW_DEL_REQUEST = 'REVIEW_DEL_REQUEST'
export const REVIEW_DEL_SUCCESS = 'REVIEW_DEL_SUCCESS'
export const REVIEW_DEL_FAIL = 'REVIEW_DEL_FAIL'

